/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustScoreRouteImport } from './routes/trust-score'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RiskAlertRouteImport } from './routes/risk-alert'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinCircleRouteImport } from './routes/join-circle'
import { Route as CreateCircleRouteImport } from './routes/create-circle'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyIndexRouteImport } from './routes/verify.index'
import { Route as VerifySelfieRouteImport } from './routes/verify.selfie'
import { Route as VerifyPhoneRouteImport } from './routes/verify.phone'
import { Route as VerifyMomoRouteImport } from './routes/verify.momo'
import { Route as VerifyGuarantorRouteImport } from './routes/verify.guarantor'
import { Route as VerifyGhanaCardRouteImport } from './routes/verify.ghana-card'
import { Route as PayoutIdRouteImport } from './routes/payout.$id'
import { Route as PaymentIdRouteImport } from './routes/payment.$id'
import { Route as CircleIdRouteImport } from './routes/circle.$id'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPaymentsRouteImport } from './routes/_app/payments'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppCirclesRouteImport } from './routes/_app/circles'
import { Route as CircleIdMembersRouteImport } from './routes/circle.$id.members'
import { Route as CircleIdApprovalsRouteImport } from './routes/circle.$id.approvals'

const TrustScoreRoute = TrustScoreRouteImport.update({
  id: '/trust-score',
  path: '/trust-score',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskAlertRoute = RiskAlertRouteImport.update({
  id: '/risk-alert',
  path: '/risk-alert',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCircleRoute = JoinCircleRouteImport.update({
  id: '/join-circle',
  path: '/join-circle',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateCircleRoute = CreateCircleRouteImport.update({
  id: '/create-circle',
  path: '/create-circle',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifySelfieRoute = VerifySelfieRouteImport.update({
  id: '/verify/selfie',
  path: '/verify/selfie',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyPhoneRoute = VerifyPhoneRouteImport.update({
  id: '/verify/phone',
  path: '/verify/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyMomoRoute = VerifyMomoRouteImport.update({
  id: '/verify/momo',
  path: '/verify/momo',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyGuarantorRoute = VerifyGuarantorRouteImport.update({
  id: '/verify/guarantor',
  path: '/verify/guarantor',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyGhanaCardRoute = VerifyGhanaCardRouteImport.update({
  id: '/verify/ghana-card',
  path: '/verify/ghana-card',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutIdRoute = PayoutIdRouteImport.update({
  id: '/payout/$id',
  path: '/payout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentIdRoute = PaymentIdRouteImport.update({
  id: '/payment/$id',
  path: '/payment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleIdRoute = CircleIdRouteImport.update({
  id: '/circle/$id',
  path: '/circle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppCirclesRoute = AppCirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => AppRoute,
} as any)
const CircleIdMembersRoute = CircleIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => CircleIdRoute,
} as any)
const CircleIdApprovalsRoute = CircleIdApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => CircleIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-circle': typeof CreateCircleRoute
  '/join-circle': typeof JoinCircleRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/risk-alert': typeof RiskAlertRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/trust-score': typeof TrustScoreRoute
  '/circles': typeof AppCirclesRoute
  '/home': typeof AppHomeRoute
  '/notifications': typeof AppNotificationsRoute
  '/payments': typeof AppPaymentsRoute
  '/profile': typeof AppProfileRoute
  '/circle/$id': typeof CircleIdRouteWithChildren
  '/payment/$id': typeof PaymentIdRoute
  '/payout/$id': typeof PayoutIdRoute
  '/verify/ghana-card': typeof VerifyGhanaCardRoute
  '/verify/guarantor': typeof VerifyGuarantorRoute
  '/verify/momo': typeof VerifyMomoRoute
  '/verify/phone': typeof VerifyPhoneRoute
  '/verify/selfie': typeof VerifySelfieRoute
  '/verify': typeof VerifyIndexRoute
  '/circle/$id/approvals': typeof CircleIdApprovalsRoute
  '/circle/$id/members': typeof CircleIdMembersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-circle': typeof CreateCircleRoute
  '/join-circle': typeof JoinCircleRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/risk-alert': typeof RiskAlertRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/trust-score': typeof TrustScoreRoute
  '/circles': typeof AppCirclesRoute
  '/home': typeof AppHomeRoute
  '/notifications': typeof AppNotificationsRoute
  '/payments': typeof AppPaymentsRoute
  '/profile': typeof AppProfileRoute
  '/circle/$id': typeof CircleIdRouteWithChildren
  '/payment/$id': typeof PaymentIdRoute
  '/payout/$id': typeof PayoutIdRoute
  '/verify/ghana-card': typeof VerifyGhanaCardRoute
  '/verify/guarantor': typeof VerifyGuarantorRoute
  '/verify/momo': typeof VerifyMomoRoute
  '/verify/phone': typeof VerifyPhoneRoute
  '/verify/selfie': typeof VerifySelfieRoute
  '/verify': typeof VerifyIndexRoute
  '/circle/$id/approvals': typeof CircleIdApprovalsRoute
  '/circle/$id/members': typeof CircleIdMembersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/create-circle': typeof CreateCircleRoute
  '/join-circle': typeof JoinCircleRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/risk-alert': typeof RiskAlertRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/trust-score': typeof TrustScoreRoute
  '/_app/circles': typeof AppCirclesRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/profile': typeof AppProfileRoute
  '/circle/$id': typeof CircleIdRouteWithChildren
  '/payment/$id': typeof PaymentIdRoute
  '/payout/$id': typeof PayoutIdRoute
  '/verify/ghana-card': typeof VerifyGhanaCardRoute
  '/verify/guarantor': typeof VerifyGuarantorRoute
  '/verify/momo': typeof VerifyMomoRoute
  '/verify/phone': typeof VerifyPhoneRoute
  '/verify/selfie': typeof VerifySelfieRoute
  '/verify': typeof VerifyIndexRoute
  '/circle/$id/approvals': typeof CircleIdApprovalsRoute
  '/circle/$id/members': typeof CircleIdMembersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-circle'
    | '/join-circle'
    | '/login'
    | '/register'
    | '/risk-alert'
    | '/settings'
    | '/transactions'
    | '/trust-score'
    | '/circles'
    | '/home'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/circle/$id'
    | '/payment/$id'
    | '/payout/$id'
    | '/verify/ghana-card'
    | '/verify/guarantor'
    | '/verify/momo'
    | '/verify/phone'
    | '/verify/selfie'
    | '/verify'
    | '/circle/$id/approvals'
    | '/circle/$id/members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-circle'
    | '/join-circle'
    | '/login'
    | '/register'
    | '/risk-alert'
    | '/settings'
    | '/transactions'
    | '/trust-score'
    | '/circles'
    | '/home'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/circle/$id'
    | '/payment/$id'
    | '/payout/$id'
    | '/verify/ghana-card'
    | '/verify/guarantor'
    | '/verify/momo'
    | '/verify/phone'
    | '/verify/selfie'
    | '/verify'
    | '/circle/$id/approvals'
    | '/circle/$id/members'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/create-circle'
    | '/join-circle'
    | '/login'
    | '/register'
    | '/risk-alert'
    | '/settings'
    | '/transactions'
    | '/trust-score'
    | '/_app/circles'
    | '/_app/home'
    | '/_app/notifications'
    | '/_app/payments'
    | '/_app/profile'
    | '/circle/$id'
    | '/payment/$id'
    | '/payout/$id'
    | '/verify/ghana-card'
    | '/verify/guarantor'
    | '/verify/momo'
    | '/verify/phone'
    | '/verify/selfie'
    | '/verify'
    | '/circle/$id/approvals'
    | '/circle/$id/members'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CreateCircleRoute: typeof CreateCircleRoute
  JoinCircleRoute: typeof JoinCircleRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RiskAlertRoute: typeof RiskAlertRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
  TrustScoreRoute: typeof TrustScoreRoute
  CircleIdRoute: typeof CircleIdRouteWithChildren
  PaymentIdRoute: typeof PaymentIdRoute
  PayoutIdRoute: typeof PayoutIdRoute
  VerifyGhanaCardRoute: typeof VerifyGhanaCardRoute
  VerifyGuarantorRoute: typeof VerifyGuarantorRoute
  VerifyMomoRoute: typeof VerifyMomoRoute
  VerifyPhoneRoute: typeof VerifyPhoneRoute
  VerifySelfieRoute: typeof VerifySelfieRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust-score': {
      id: '/trust-score'
      path: '/trust-score'
      fullPath: '/trust-score'
      preLoaderRoute: typeof TrustScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-alert': {
      id: '/risk-alert'
      path: '/risk-alert'
      fullPath: '/risk-alert'
      preLoaderRoute: typeof RiskAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-circle': {
      id: '/join-circle'
      path: '/join-circle'
      fullPath: '/join-circle'
      preLoaderRoute: typeof JoinCircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-circle': {
      id: '/create-circle'
      path: '/create-circle'
      fullPath: '/create-circle'
      preLoaderRoute: typeof CreateCircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/selfie': {
      id: '/verify/selfie'
      path: '/verify/selfie'
      fullPath: '/verify/selfie'
      preLoaderRoute: typeof VerifySelfieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/phone': {
      id: '/verify/phone'
      path: '/verify/phone'
      fullPath: '/verify/phone'
      preLoaderRoute: typeof VerifyPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/momo': {
      id: '/verify/momo'
      path: '/verify/momo'
      fullPath: '/verify/momo'
      preLoaderRoute: typeof VerifyMomoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/guarantor': {
      id: '/verify/guarantor'
      path: '/verify/guarantor'
      fullPath: '/verify/guarantor'
      preLoaderRoute: typeof VerifyGuarantorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/ghana-card': {
      id: '/verify/ghana-card'
      path: '/verify/ghana-card'
      fullPath: '/verify/ghana-card'
      preLoaderRoute: typeof VerifyGhanaCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payout/$id': {
      id: '/payout/$id'
      path: '/payout/$id'
      fullPath: '/payout/$id'
      preLoaderRoute: typeof PayoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$id': {
      id: '/payment/$id'
      path: '/payment/$id'
      fullPath: '/payment/$id'
      preLoaderRoute: typeof PaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle/$id': {
      id: '/circle/$id'
      path: '/circle/$id'
      fullPath: '/circle/$id'
      preLoaderRoute: typeof CircleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/circles': {
      id: '/_app/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof AppCirclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/circle/$id/members': {
      id: '/circle/$id/members'
      path: '/members'
      fullPath: '/circle/$id/members'
      preLoaderRoute: typeof CircleIdMembersRouteImport
      parentRoute: typeof CircleIdRoute
    }
    '/circle/$id/approvals': {
      id: '/circle/$id/approvals'
      path: '/approvals'
      fullPath: '/circle/$id/approvals'
      preLoaderRoute: typeof CircleIdApprovalsRouteImport
      parentRoute: typeof CircleIdRoute
    }
  }
}

interface AppRouteChildren {
  AppCirclesRoute: typeof AppCirclesRoute
  AppHomeRoute: typeof AppHomeRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProfileRoute: typeof AppProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCirclesRoute: AppCirclesRoute,
  AppHomeRoute: AppHomeRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProfileRoute: AppProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CircleIdRouteChildren {
  CircleIdApprovalsRoute: typeof CircleIdApprovalsRoute
  CircleIdMembersRoute: typeof CircleIdMembersRoute
}

const CircleIdRouteChildren: CircleIdRouteChildren = {
  CircleIdApprovalsRoute: CircleIdApprovalsRoute,
  CircleIdMembersRoute: CircleIdMembersRoute,
}

const CircleIdRouteWithChildren = CircleIdRoute._addFileChildren(
  CircleIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CreateCircleRoute: CreateCircleRoute,
  JoinCircleRoute: JoinCircleRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RiskAlertRoute: RiskAlertRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
  TrustScoreRoute: TrustScoreRoute,
  CircleIdRoute: CircleIdRouteWithChildren,
  PaymentIdRoute: PaymentIdRoute,
  PayoutIdRoute: PayoutIdRoute,
  VerifyGhanaCardRoute: VerifyGhanaCardRoute,
  VerifyGuarantorRoute: VerifyGuarantorRoute,
  VerifyMomoRoute: VerifyMomoRoute,
  VerifyPhoneRoute: VerifyPhoneRoute,
  VerifySelfieRoute: VerifySelfieRoute,
  VerifyIndexRoute: VerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
