/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustScoreRouteImport } from './routes/trust-score'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RiskAlertRouteImport } from './routes/risk-alert'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinCircleRouteImport } from './routes/join-circle'
import { Route as CreateCircleRouteImport } from './routes/create-circle'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyIndexRouteImport } from './routes/verify.index'
import { Route as VerifyStatusRouteImport } from './routes/verify.status'
import { Route as VerifySelfieRouteImport } from './routes/verify.selfie'
import { Route as VerifyProfileRouteImport } from './routes/verify.profile'
import { Route as VerifyPhoneRouteImport } from './routes/verify.phone'
import { Route as VerifyMomoRouteImport } from './routes/verify.momo'
import { Route as VerifyGuarantorRouteImport } from './routes/verify.guarantor'
import { Route as VerifyGhanaCardRouteImport } from './routes/verify.ghana-card'
import { Route as PayoutIdRouteImport } from './routes/payout.$id'
import { Route as PiggyBagIdRouteImport } from './routes/piggy-bag.$id'
import { Route as PiggyBagCreateRouteImport } from './routes/piggy-bag.create'
import { Route as PaymentIdRouteImport } from './routes/payment.$id'
import { Route as CircleIdRouteImport } from './routes/circle.$id'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AppPiggyBagRouteImport } from './routes/_app/piggy-bag'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPaymentsRouteImport } from './routes/_app/payments'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppCirclesRouteImport } from './routes/_app/circles'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as AdminAdminCirclesRouteImport } from './routes/_admin.admin.circles'
import { Route as CircleIdMembersRouteImport } from './routes/circle.$id.members'
import { Route as CircleIdApprovalsRouteImport } from './routes/circle.$id.approvals'
import { Route as AdminAdminVerificationsRouteImport } from './routes/_admin.admin.verifications'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'

const TrustScoreRoute = TrustScoreRouteImport.update({
  id: '/trust-score',
  path: '/trust-score',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskAlertRoute = RiskAlertRouteImport.update({
  id: '/risk-alert',
  path: '/risk-alert',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCircleRoute = JoinCircleRouteImport.update({
  id: '/join-circle',
  path: '/join-circle',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateCircleRoute = CreateCircleRouteImport.update({
  id: '/create-circle',
  path: '/create-circle',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyStatusRoute = VerifyStatusRouteImport.update({
  id: '/verify/status',
  path: '/verify/status',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifySelfieRoute = VerifySelfieRouteImport.update({
  id: '/verify/selfie',
  path: '/verify/selfie',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyProfileRoute = VerifyProfileRouteImport.update({
  id: '/verify/profile',
  path: '/verify/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyPhoneRoute = VerifyPhoneRouteImport.update({
  id: '/verify/phone',
  path: '/verify/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyMomoRoute = VerifyMomoRouteImport.update({
  id: '/verify/momo',
  path: '/verify/momo',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyGuarantorRoute = VerifyGuarantorRouteImport.update({
  id: '/verify/guarantor',
  path: '/verify/guarantor',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyGhanaCardRoute = VerifyGhanaCardRouteImport.update({
  id: '/verify/ghana-card',
  path: '/verify/ghana-card',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutIdRoute = PayoutIdRouteImport.update({
  id: '/payout/$id',
  path: '/payout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PiggyBagIdRoute = PiggyBagIdRouteImport.update({
  id: '/piggy-bag/$id',
  path: '/piggy-bag/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PiggyBagCreateRoute = PiggyBagCreateRouteImport.update({
  id: '/piggy-bag/create',
  path: '/piggy-bag/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentIdRoute = PaymentIdRouteImport.update({
  id: '/payment/$id',
  path: '/payment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleIdRoute = CircleIdRouteImport.update({
  id: '/circle/$id',
  path: '/circle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPiggyBagRoute = AppPiggyBagRouteImport.update({
  id: '/piggy-bag',
  path: '/piggy-bag',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppCirclesRoute = AppCirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCirclesRoute = AdminAdminCirclesRouteImport.update({
  id: '/admin/circles',
  path: '/admin/circles',
  getParentRoute: () => AdminRoute,
} as any)
const CircleIdMembersRoute = CircleIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => CircleIdRoute,
} as any)
const CircleIdApprovalsRoute = CircleIdApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => CircleIdRoute,
} as any)
const AdminAdminVerificationsRoute = AdminAdminVerificationsRouteImport.update({
  id: '/admin/verifications',
  path: '/admin/verifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-circle': typeof CreateCircleRoute
  '/join-circle': typeof JoinCircleRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/risk-alert': typeof RiskAlertRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/trust-score': typeof TrustScoreRoute
  '/circles': typeof AppCirclesRoute
  '/home': typeof AppHomeRoute
  '/notifications': typeof AppNotificationsRoute
  '/payments': typeof AppPaymentsRoute
  '/profile': typeof AppProfileRoute
  '/admin/login': typeof AdminLoginRoute
  '/circle/$id': typeof CircleIdRouteWithChildren
  '/payment/$id': typeof PaymentIdRoute
  '/piggy-bag/create': typeof PiggyBagCreateRoute
  '/piggy-bag/$id': typeof PiggyBagIdRoute
  '/payout/$id': typeof PayoutIdRoute
  '/piggy-bag': typeof AppPiggyBagRoute
  '/verify/ghana-card': typeof VerifyGhanaCardRoute
  '/verify/guarantor': typeof VerifyGuarantorRoute
  '/verify/momo': typeof VerifyMomoRoute
  '/verify/phone': typeof VerifyPhoneRoute
  '/verify/profile': typeof VerifyProfileRoute
  '/verify/selfie': typeof VerifySelfieRoute
  '/verify/status': typeof VerifyStatusRoute
  '/verify/': typeof VerifyIndexRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/verifications': typeof AdminAdminVerificationsRoute
  '/admin/circles': typeof AdminAdminCirclesRoute
  '/circle/$id/approvals': typeof CircleIdApprovalsRoute
  '/circle/$id/members': typeof CircleIdMembersRoute
  '/admin/': typeof AdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-circle': typeof CreateCircleRoute
  '/join-circle': typeof JoinCircleRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/risk-alert': typeof RiskAlertRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/trust-score': typeof TrustScoreRoute
  '/circles': typeof AppCirclesRoute
  '/home': typeof AppHomeRoute
  '/notifications': typeof AppNotificationsRoute
  '/payments': typeof AppPaymentsRoute
  '/profile': typeof AppProfileRoute
  '/admin/login': typeof AdminLoginRoute
  '/circle/$id': typeof CircleIdRouteWithChildren
  '/payment/$id': typeof PaymentIdRoute
  '/piggy-bag/create': typeof PiggyBagCreateRoute
  '/piggy-bag/$id': typeof PiggyBagIdRoute
  '/payout/$id': typeof PayoutIdRoute
  '/piggy-bag': typeof AppPiggyBagRoute
  '/verify/ghana-card': typeof VerifyGhanaCardRoute
  '/verify/guarantor': typeof VerifyGuarantorRoute
  '/verify/momo': typeof VerifyMomoRoute
  '/verify/phone': typeof VerifyPhoneRoute
  '/verify/profile': typeof VerifyProfileRoute
  '/verify/selfie': typeof VerifySelfieRoute
  '/verify/status': typeof VerifyStatusRoute
  '/verify': typeof VerifyIndexRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/verifications': typeof AdminAdminVerificationsRoute
  '/admin/circles': typeof AdminAdminCirclesRoute
  '/circle/$id/approvals': typeof CircleIdApprovalsRoute
  '/circle/$id/members': typeof CircleIdMembersRoute
  '/admin': typeof AdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/create-circle': typeof CreateCircleRoute
  '/join-circle': typeof JoinCircleRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/risk-alert': typeof RiskAlertRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/trust-score': typeof TrustScoreRoute
  '/_app/circles': typeof AppCirclesRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/profile': typeof AppProfileRoute
  '/admin/login': typeof AdminLoginRoute
  '/circle/$id': typeof CircleIdRouteWithChildren
  '/payment/$id': typeof PaymentIdRoute
  '/piggy-bag/create': typeof PiggyBagCreateRoute
  '/piggy-bag/$id': typeof PiggyBagIdRoute
  '/payout/$id': typeof PayoutIdRoute
  '/_app/piggy-bag': typeof AppPiggyBagRoute
  '/verify/ghana-card': typeof VerifyGhanaCardRoute
  '/verify/guarantor': typeof VerifyGuarantorRoute
  '/verify/momo': typeof VerifyMomoRoute
  '/verify/phone': typeof VerifyPhoneRoute
  '/verify/profile': typeof VerifyProfileRoute
  '/verify/selfie': typeof VerifySelfieRoute
  '/verify/status': typeof VerifyStatusRoute
  '/verify/': typeof VerifyIndexRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_admin/admin/verifications': typeof AdminAdminVerificationsRoute
  '/_admin/admin/circles': typeof AdminAdminCirclesRoute
  '/circle/$id/approvals': typeof CircleIdApprovalsRoute
  '/circle/$id/members': typeof CircleIdMembersRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-circle'
    | '/join-circle'
    | '/login'
    | '/register'
    | '/risk-alert'
    | '/settings'
    | '/transactions'
    | '/trust-score'
    | '/circles'
    | '/home'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/admin/login'
    | '/circle/$id'
    | '/payment/$id'
    | '/piggy-bag/create'
    | '/piggy-bag/$id'
    | '/payout/$id'
    | '/piggy-bag'
    | '/verify/ghana-card'
    | '/verify/guarantor'
    | '/verify/momo'
    | '/verify/phone'
    | '/verify/profile'
    | '/verify/selfie'
    | '/verify/status'
    | '/verify/'
    | '/admin/users'
    | '/admin/verifications'
    | '/admin/circles'
    | '/circle/$id/approvals'
    | '/circle/$id/members'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-circle'
    | '/join-circle'
    | '/login'
    | '/register'
    | '/risk-alert'
    | '/settings'
    | '/transactions'
    | '/trust-score'
    | '/circles'
    | '/home'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/admin/login'
    | '/circle/$id'
    | '/payment/$id'
    | '/piggy-bag/create'
    | '/piggy-bag/$id'
    | '/payout/$id'
    | '/piggy-bag'
    | '/verify/ghana-card'
    | '/verify/guarantor'
    | '/verify/momo'
    | '/verify/phone'
    | '/verify/profile'
    | '/verify/selfie'
    | '/verify/status'
    | '/verify'
    | '/admin/users'
    | '/admin/verifications'
    | '/admin/circles'
    | '/circle/$id/approvals'
    | '/circle/$id/members'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_app'
    | '/create-circle'
    | '/join-circle'
    | '/login'
    | '/register'
    | '/risk-alert'
    | '/settings'
    | '/transactions'
    | '/trust-score'
    | '/_app/circles'
    | '/_app/home'
    | '/_app/notifications'
    | '/_app/payments'
    | '/_app/profile'
    | '/admin/login'
    | '/circle/$id'
    | '/payment/$id'
    | '/piggy-bag/create'
    | '/piggy-bag/$id'
    | '/payout/$id'
    | '/_app/piggy-bag'
    | '/verify/ghana-card'
    | '/verify/guarantor'
    | '/verify/momo'
    | '/verify/phone'
    | '/verify/profile'
    | '/verify/selfie'
    | '/verify/status'
    | '/verify/'
    | '/_admin/admin/users'
    | '/_admin/admin/verifications'
    | '/_admin/admin/circles'
    | '/circle/$id/approvals'
    | '/circle/$id/members'
    | '/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CreateCircleRoute: typeof CreateCircleRoute
  JoinCircleRoute: typeof JoinCircleRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RiskAlertRoute: typeof RiskAlertRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
  TrustScoreRoute: typeof TrustScoreRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CircleIdRoute: typeof CircleIdRouteWithChildren
  PaymentIdRoute: typeof PaymentIdRoute
  PiggyBagCreateRoute: typeof PiggyBagCreateRoute
  PiggyBagIdRoute: typeof PiggyBagIdRoute
  PayoutIdRoute: typeof PayoutIdRoute
  VerifyGhanaCardRoute: typeof VerifyGhanaCardRoute
  VerifyGuarantorRoute: typeof VerifyGuarantorRoute
  VerifyMomoRoute: typeof VerifyMomoRoute
  VerifyPhoneRoute: typeof VerifyPhoneRoute
  VerifyProfileRoute: typeof VerifyProfileRoute
  VerifySelfieRoute: typeof VerifySelfieRoute
  VerifyStatusRoute: typeof VerifyStatusRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust-score': {
      id: '/trust-score'
      path: '/trust-score'
      fullPath: '/trust-score'
      preLoaderRoute: typeof TrustScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-alert': {
      id: '/risk-alert'
      path: '/risk-alert'
      fullPath: '/risk-alert'
      preLoaderRoute: typeof RiskAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-circle': {
      id: '/join-circle'
      path: '/join-circle'
      fullPath: '/join-circle'
      preLoaderRoute: typeof JoinCircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-circle': {
      id: '/create-circle'
      path: '/create-circle'
      fullPath: '/create-circle'
      preLoaderRoute: typeof CreateCircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/status': {
      id: '/verify/status'
      path: '/verify/status'
      fullPath: '/verify/status'
      preLoaderRoute: typeof VerifyStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/selfie': {
      id: '/verify/selfie'
      path: '/verify/selfie'
      fullPath: '/verify/selfie'
      preLoaderRoute: typeof VerifySelfieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/profile': {
      id: '/verify/profile'
      path: '/verify/profile'
      fullPath: '/verify/profile'
      preLoaderRoute: typeof VerifyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/phone': {
      id: '/verify/phone'
      path: '/verify/phone'
      fullPath: '/verify/phone'
      preLoaderRoute: typeof VerifyPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/momo': {
      id: '/verify/momo'
      path: '/verify/momo'
      fullPath: '/verify/momo'
      preLoaderRoute: typeof VerifyMomoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/guarantor': {
      id: '/verify/guarantor'
      path: '/verify/guarantor'
      fullPath: '/verify/guarantor'
      preLoaderRoute: typeof VerifyGuarantorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/ghana-card': {
      id: '/verify/ghana-card'
      path: '/verify/ghana-card'
      fullPath: '/verify/ghana-card'
      preLoaderRoute: typeof VerifyGhanaCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payout/$id': {
      id: '/payout/$id'
      path: '/payout/$id'
      fullPath: '/payout/$id'
      preLoaderRoute: typeof PayoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piggy-bag/$id': {
      id: '/piggy-bag/$id'
      path: '/piggy-bag/$id'
      fullPath: '/piggy-bag/$id'
      preLoaderRoute: typeof PiggyBagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piggy-bag/create': {
      id: '/piggy-bag/create'
      path: '/piggy-bag/create'
      fullPath: '/piggy-bag/create'
      preLoaderRoute: typeof PiggyBagCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$id': {
      id: '/payment/$id'
      path: '/payment/$id'
      fullPath: '/payment/$id'
      preLoaderRoute: typeof PaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle/$id': {
      id: '/circle/$id'
      path: '/circle/$id'
      fullPath: '/circle/$id'
      preLoaderRoute: typeof CircleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/piggy-bag': {
      id: '/_app/piggy-bag'
      path: '/piggy-bag'
      fullPath: '/piggy-bag'
      preLoaderRoute: typeof AppPiggyBagRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/circles': {
      id: '/_app/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof AppCirclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/circles': {
      id: '/_admin/admin/circles'
      path: '/admin/circles'
      fullPath: '/admin/circles'
      preLoaderRoute: typeof AdminAdminCirclesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/circle/$id/members': {
      id: '/circle/$id/members'
      path: '/members'
      fullPath: '/circle/$id/members'
      preLoaderRoute: typeof CircleIdMembersRouteImport
      parentRoute: typeof CircleIdRoute
    }
    '/circle/$id/approvals': {
      id: '/circle/$id/approvals'
      path: '/approvals'
      fullPath: '/circle/$id/approvals'
      preLoaderRoute: typeof CircleIdApprovalsRouteImport
      parentRoute: typeof CircleIdRoute
    }
    '/_admin/admin/verifications': {
      id: '/_admin/admin/verifications'
      path: '/admin/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminAdminVerificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminCirclesRoute: typeof AdminAdminCirclesRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminVerificationsRoute: typeof AdminAdminVerificationsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminCirclesRoute: AdminAdminCirclesRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminVerificationsRoute: AdminAdminVerificationsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppCirclesRoute: typeof AppCirclesRoute
  AppHomeRoute: typeof AppHomeRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPiggyBagRoute: typeof AppPiggyBagRoute
  AppProfileRoute: typeof AppProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCirclesRoute: AppCirclesRoute,
  AppHomeRoute: AppHomeRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPiggyBagRoute: AppPiggyBagRoute,
  AppProfileRoute: AppProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CircleIdRouteChildren {
  CircleIdApprovalsRoute: typeof CircleIdApprovalsRoute
  CircleIdMembersRoute: typeof CircleIdMembersRoute
}

const CircleIdRouteChildren: CircleIdRouteChildren = {
  CircleIdApprovalsRoute: CircleIdApprovalsRoute,
  CircleIdMembersRoute: CircleIdMembersRoute,
}

const CircleIdRouteWithChildren = CircleIdRoute._addFileChildren(
  CircleIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CreateCircleRoute: CreateCircleRoute,
  JoinCircleRoute: JoinCircleRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RiskAlertRoute: RiskAlertRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
  TrustScoreRoute: TrustScoreRoute,
  AdminLoginRoute: AdminLoginRoute,
  CircleIdRoute: CircleIdRouteWithChildren,
  PaymentIdRoute: PaymentIdRoute,
  PiggyBagCreateRoute: PiggyBagCreateRoute,
  PiggyBagIdRoute: PiggyBagIdRoute,
  PayoutIdRoute: PayoutIdRoute,
  VerifyGhanaCardRoute: VerifyGhanaCardRoute,
  VerifyGuarantorRoute: VerifyGuarantorRoute,
  VerifyMomoRoute: VerifyMomoRoute,
  VerifyPhoneRoute: VerifyPhoneRoute,
  VerifyProfileRoute: VerifyProfileRoute,
  VerifySelfieRoute: VerifySelfieRoute,
  VerifyStatusRoute: VerifyStatusRoute,
  VerifyIndexRoute: VerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
